# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
