# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0003_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='leap_prep_status',
            field=models.IntegerField(choices=[('NO DATA', 'NO DATA'), ('DONE', 'DONE'), ('WAIT', 'WAIT'), ('ERROR', 'ERROR')], default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='leap_status',
            field=models.IntegerField(choices=[('NO DATA', 'NO DATA'), ('DONE', 'DONE'), ('WAIT', 'WAIT'), ('ERROR', 'ERROR')], default=0),
        ),
    ]
