# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0004_auto_20170819_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='nres',
            field=models.IntegerField(default=0),
        ),
    ]
