# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0005_auto_20170819_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(default='Default Work', max_length=20),
        ),
    ]
