# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0006_auto_20170819_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='eq_prep_status',
            field=models.IntegerField(choices=[(0, 'NO DATA'), (1, 'DONE'), (2, 'WAIT'), (3, 'ERROR')], default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='eq_run_status',
            field=models.IntegerField(choices=[(0, 'NO DATA'), (1, 'DONE'), (2, 'WAIT'), (3, 'ERROR')], default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='leap_prep_status',
            field=models.IntegerField(choices=[(0, 'NO DATA'), (1, 'DONE'), (2, 'WAIT'), (3, 'ERROR')], default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='leap_status',
            field=models.IntegerField(choices=[(0, 'NO DATA'), (1, 'DONE'), (2, 'WAIT'), (3, 'ERROR')], default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='md_prep_status',
            field=models.IntegerField(choices=[(0, 'NO DATA'), (1, 'DONE'), (2, 'WAIT'), (3, 'ERROR')], default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='md_run_status',
            field=models.IntegerField(choices=[(0, 'NO DATA'), (1, 'DONE'), (2, 'WAIT'), (3, 'ERROR')], default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='min_prep_status',
            field=models.IntegerField(choices=[(0, 'NO DATA'), (1, 'DONE'), (2, 'WAIT'), (3, 'ERROR')], default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='min_run_status',
            field=models.IntegerField(choices=[(0, 'NO DATA'), (1, 'DONE'), (2, 'WAIT'), (3, 'ERROR')], default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='ptraj_prep_status',
            field=models.IntegerField(choices=[(0, 'NO DATA'), (1, 'DONE'), (2, 'WAIT'), (3, 'ERROR')], default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='ptraj_run_status',
            field=models.IntegerField(choices=[(0, 'NO DATA'), (1, 'DONE'), (2, 'WAIT'), (3, 'ERROR')], default=0),
        ),
    ]
