# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0007_auto_20170819_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdjob',
            name='dt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mdjob',
            name='nstlim',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mdjob',
            name='ntb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mdjob',
            name='pressure',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mdjob',
            name='sim_begin_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mdjob',
            name='sim_end_time',
            field=models.FloatField(default=0),
        ),
    ]
