# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0009_auto_20170821_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdjob',
            name='prep_status',
            field=models.IntegerField(choices=[(0, 'NO DATA'), (1, 'DONE'), (2, 'WAIT'), (3, 'ERROR')], default=0),
        ),
        migrations.AddField(
            model_name='mdjob',
            name='run_status',
            field=models.IntegerField(choices=[(0, 'NO DATA'), (1, 'DONE'), (2, 'WAIT'), (3, 'ERROR')], default=0),
        ),
        migrations.AddField(
            model_name='ptrajjob',
            name='prep_status',
            field=models.IntegerField(choices=[(0, 'NO DATA'), (1, 'DONE'), (2, 'WAIT'), (3, 'ERROR')], default=0),
        ),
        migrations.AddField(
            model_name='ptrajjob',
            name='run_status',
            field=models.IntegerField(choices=[(0, 'NO DATA'), (1, 'DONE'), (2, 'WAIT'), (3, 'ERROR')], default=0),
        ),
    ]
