# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0011_auto_20170824_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqjob',
            name='work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eqjobs', to='webmd.Work'),
        ),
        migrations.AlterField(
            model_name='minjob',
            name='work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minjobs', to='webmd.Work'),
        ),
    ]
