# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0013_auto_20170824_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='leap_prep_status',
        ),
        migrations.RemoveField(
            model_name='work',
            name='leap_status',
        ),
    ]
