# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0014_auto_20170831_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdjob',
            name='prep_status',
        ),
        migrations.RemoveField(
            model_name='ptrajjob',
            name='prep_status',
        ),
        migrations.RemoveField(
            model_name='work',
            name='eq_prep_status',
        ),
        migrations.RemoveField(
            model_name='work',
            name='eq_run_status',
        ),
        migrations.RemoveField(
            model_name='work',
            name='min_prep_status',
        ),
        migrations.RemoveField(
            model_name='work',
            name='min_run_status',
        ),
    ]
