# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0015_auto_20170831_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdjob',
            name='run_status',
        ),
        migrations.RemoveField(
            model_name='ptrajjob',
            name='run_status',
        ),
    ]
