# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0016_auto_20170831_0916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='eqjob',
            name='job_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mdjob',
            name='job_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='minjob',
            name='job_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ptrajjob',
            name='job_id',
            field=models.IntegerField(null=True),
        ),
    ]
