# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0017_auto_20170906_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='job_id',
            field=models.IntegerField(null=True),
        ),
    ]
