# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0018_work_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='cut',
            field=models.FloatField(default=9.0),
        ),
        migrations.AddField(
            model_name='work',
            name='potassium_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='buffer_size',
            field=models.FloatField(default=10.0),
        ),
    ]
