# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0019_auto_20171020_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='anion',
            field=models.CharField(default='Cl-', max_length=5),
        ),
        migrations.AddField(
            model_name='work',
            name='cation',
            field=models.CharField(default='Na+', max_length=5),
        ),
    ]
