# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0020_auto_20171025_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='chloride_added',
        ),
        migrations.RemoveField(
            model_name='work',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='work',
            name='potassium_added',
        ),
        migrations.RemoveField(
            model_name='work',
            name='sodium_added',
        ),
        migrations.AddField(
            model_name='work',
            name='ref_temp',
            field=models.IntegerField(default=300),
        ),
    ]
