# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0022_usermeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eqjob',
            name='work',
        ),
        migrations.RemoveField(
            model_name='minjob',
            name='work',
        ),
        migrations.DeleteModel(
            name='Eqjob',
        ),
        migrations.DeleteModel(
            name='Minjob',
        ),
    ]
