# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0023_auto_20180125_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
