# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0024_work_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
