# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-03 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0025_work_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdjob',
            name='work',
        ),
        migrations.RemoveField(
            model_name='ptrajjob',
            name='work',
        ),
        migrations.DeleteModel(
            name='Mdjob',
        ),
        migrations.DeleteModel(
            name='Ptrajjob',
        ),
    ]
