# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0026_auto_20180203_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkJob',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('work_id', models.IntegerField()),
            ],
        ),
    ]
