# Generated by Django 2.0.2 on 2018-06-19 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webmd', '0027_workjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=500)),
                ('file', models.CharField(max_length=500)),
                ('cut', models.FloatField(default=9.0)),
                ('buffer_size', models.FloatField(default=10.0)),
                ('solvent_model', models.CharField(default='TIP3PBOX', max_length=15)),
                ('cation', models.CharField(default='Na+', max_length=5)),
                ('anion', models.CharField(default='Cl-', max_length=5)),
                ('ref_temp', models.IntegerField(default=300)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
