# Generated by Django 2.1 on 2018-11-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0029_auto_20180717_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='work_dir',
            new_name='work_dir_old',
        ),
    ]
