# Generated by Django 2.1 on 2018-11-22 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmd', '0030_auto_20181115_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAnalysisJob',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('anal_serial', models.IntegerField()),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webmd.Work')),
            ],
        ),
    ]
