version: "3"
services:
  db:
    image: postgres
    hostname: db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  controller:
    depends_on:
      - db
    build: .
    image: nbcc/prowave-controller
    hostname: slurmctld
    extra_hosts:
      # - gpu67:172.16.3.67
      - gpu68:172.16.3.68
      - gpu69:172.16.3.69
    ports:
      - 8000:8000
      - 6817:6817
      - 6379:6379
    volumes:
      - .:/home/nbcc/www/prowave
      - ../prowave_ui:/home/nbcc/www/prowave_ui
      - ../prowave_compute:/home/nbcc/www/prowave_compute
      - ./_artifacts_/etc_slurm:/etc/slurm
      - ./data:/data
    environment:
      - PROWAVE_DB_HOST=db

volumes:
  pgdata:
    external: true
