# Generated by Django 2.1 on 2018-12-14 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visited_url', models.URLField()),
                ('ip_addr', models.GenericIPAddressField()),
                ('country_code', models.CharField(max_length=10)),
                ('country_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True)),
                ('longitude', models.FloatField(blank=True)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('organization', models.CharField(blank=True, max_length=500)),
                ('connecton_type', models.CharField(blank=True, max_length=200)),
                ('loggedin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('work_dir', models.CharField(blank=True, max_length=500)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prowave_works', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_id', models.IntegerField(null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('org1', models.CharField(blank=True, default='', max_length=500)),
                ('ip_addr', models.GenericIPAddressField()),
                ('country_code', models.CharField(max_length=10)),
                ('country_name', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=500)),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('mode', models.CharField(max_length=5)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('solvent', models.CharField(max_length=100)),
                ('box_size', models.CharField(max_length=50)),
                ('grid_size', models.CharField(max_length=50)),
                ('position', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(blank=True, default='', max_length=20)),
                ('num_residues', models.IntegerField(null=True)),
                ('protocol', models.TextField(null=True)),
                ('net_charge', models.IntegerField(null=True)),
                ('filename', models.CharField(max_length=50, null=True)),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prowave.Work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('work_id', models.IntegerField()),
                ('work_type', models.CharField(choices=[('sfe', 'Solvation Free Energy'), ('ba', 'Binding Affinity')], default='sfe', max_length=50)),
            ],
        ),
    ]
