# Generated by Django 2.1 on 2019-03-21 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prowave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='work_dir',
        ),
    ]
