# Generated by Django 2.1 on 2019-03-22 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prowave', '0002_remove_work_work_dir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinfo',
            name='work',
        ),
        migrations.RemoveField(
            model_name='workhistory',
            name='title',
        ),
        migrations.DeleteModel(
            name='WorkInfo',
        ),
    ]
